spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:${DATABASE_TYPE:postgresql}://${DB_HOST:localhost}:${DB_PORT:5432}/${DATABASE_NAME:ocean}?currentSchema=${DB_SCHEMA:ocean}
    username: ${DB_USER:sai}
    password: ${DB_PASSWORD:sai}

  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}
    driver-class-name: ${spring.datasource.driver-class-name}

jwt:
  secret:
    key: 743777217A25432A462D4A614E645267556B58703272357538782F413F442847